session_name: build
start_directory: /mnt/code/repos/build
windows:
  - window_name: k9s
    panes:
      - shell_command:
        - k9s
  - window_name: jenklib
    panes:
      - shell_command:
        - pwd
        start_directory: /mnt/code/repos/build/library-build
  - window_name: podlib
    panes:
      - shell_command:
        - pwd
        start_directory: /mnt/code/repos/build/library-pod-definition
  - window_name: prlib
    panes:
      - shell_command:
        - pwd
        start_directory: /mnt/code/repos/build/library-pr-ci
  - window_name: sharedlib
    panes:
      - shell_command:
        - pwd
        start_directory: /mnt/code/repos/build/library-shared
